init -1 python:
    ArthurRomance = {
        "Choice_ArthurRank1Convo1_1839": "Що змусило тебе стати солдатом?",
        "Choice_ArthurRank1Convo1_1840": "Яким було ваше дитинство? Твоє й Елеонори?",
        "Choice_ArthurRank1Convo1_1841": "Розкажи мені про себе.",
        "Choice_ArthurRank1Convo1_1842": "Ага. А воно хіба не так працює?",
        "Choice_ArthurRank1Convo1_1844": "А що не так?",
        "Choice_ArthurRank1Convo1_1846": "Гаразд, не звертай уваги.",#[Кінець]
        "Choice_ArthurRank1Convo1_1850": "Ой. Ніжна тема?",
        "Choice_ArthurRank1Convo1_1851": "Зажди. Що?",
        "Choice_ArthurRank1Convo1_1853": "Ні, напевно ні.",
        "Choice_ArthurRank1Convo1_1854": "Мені шкода.",
        "Choice_ArthurRank1Convo1_1855": "Просто хочу пізнати тебе більше.",
        "Choice_ArthurRank1Convo1_1857": "То як я це маю зробити?",
        "Choice_ArthurRank1Convo1_1858": "То мені припинити просто зараз чи?..",
        "Choice_ArthurRank1Convo1_1863": "Спершу напої. *Потім* особисті питання. Ясненько.",
        "Choice_ArthurRank1Convo1_1864": "Не вартує клопотів, не зважай.",#[Кінець]
        "Choice_ArthurRank1Convo1_1867": "Ем… який улюблений колір?",
        "Choice_ArthurRank1Convo1_1869": "Ем… середнє ім’я.",
        "Choice_ArthurRank1Convo1_1870": "Перший улюбленець.",
        "Choice_ArthurRank1Convo1_1872": "Чорний.",
        "Choice_ArthurRank1Convo1_1873": "Зелений.",
        "Choice_ArthurRank1Convo1_1874": "Синій.",
        "Choice_ArthurRank1Convo1_1875": "Червоний.",
        "Choice_ArthurRank1Convo1_1882": "Узагалі-то я не знаю таких подробиць про вас двох.",
        "Choice_ArthurRank1Convo1_1883": "Хай там як, але чорний навіть не колір.",#[Кінець]
        "Choice_ArthurRank1Convo1_1887": "Мені хотілося би змінити це.",
        "Choice_ArthurRank1Convo1_1888": "З таким ставленням і не дізнаєшся.",#[Кінець]
        "Choice_ArthurRank1Convo1_1892": "Бандана на твоїй скані.",
        "Choice_ArthurRank1Convo1_1893": "За «відчуттями» ти з червоних.",
        "Choice_ArthurRank1Convo1_1896": "А звідкіля взагалі той меч? Схоже, він завжди з тобою.",
        "Choice_ArthurRank1Convo1_1899": "Брекстон",
        "Choice_ArthurRank1Convo1_1900": "Герберт",
        "Choice_ArthurRank1Convo1_1901": "Джеймс",
        "Choice_ArthurRank1Convo1_1902": "Пітерсгем",
        "Choice_ArthurRank1Convo1_1908": "Це просто випадкова здогадка.",
        "Choice_ArthurRank1Convo1_1909": "Ти «відчуваєшся» як Джеймс.",
        "Choice_ArthurRank1Convo1_1911": "Мені шкода, що я не знаю оновленого списку британських імен 20 століття!",
        "Choice_ArthurRank1Convo1_1912": "А мені звідкіля це знати?",
        "Choice_ArthurRank1Convo1_1915": "Обережніше, бо почну так називати весь час.",
        "Choice_ArthurRank1Convo1_1916": "Так-так. Смійся на здоров’я.",
        "Choice_ArthurRank1Convo1_1921": "Як мило.",
        "Choice_ArthurRank1Convo1_1922": "Нудне.",
        "Choice_ArthurRank1Convo1_1924": "Так. Скажімо, на зараз досить.",
        "Choice_ArthurRank1Convo1_1925": "Звичайно, якщо ти більше нічим не хочеш поділитися.",
        "Choice_ArthurRank1Convo1_1926": "А де і як ви жили? Ну, до цього всього?",
        "Choice_ArthurRank1Convo1_1927": "Навчаюся у найкмітливіших. ;)",
        "Choice_ArthurRank1Convo1_1930": "Зарано питаю?",
        "Choice_ArthurRank1Convo1_1935": "Вартувало спробувати.",
        "Choice_ArthurRank1Convo1_2165": "О-о, ну гаразд. Не зважай.", #[Кінець]
        "Choice_ArthurRank1Convo1_3647": "Гадаю, що ти усунув проблеми з водою?",
        "Choice_ArthurRank1Convo1_3648": "Ого. Як мило.",
        "Choice_ArthurRank1Convo1_3652": "Га? Чому ні?",
        "Choice_ArthurRank1Convo1_3653": "І як ти почувався?",
        "TxtArthur_ArthurRank1Convo1_1843": "Що, отак просто?",
        "TxtArthur_ArthurRank1Convo1_1845": "Ні.",
        "TxtArthur_ArthurRank1Convo1_1847": "Заради Сола, ти…",
        "TxtArthur_ArthurRank1Convo1_1848": "А, ну так. Тебе ж заблокували в альтернативному вимірі.",
        "TxtArthur_ArthurRank1Convo1_1849": "Ти не маєш такої звички до «людей», як я.",
        "TxtArthur_ArthurRank1Convo1_1852": "Ти думаєш, що я достатньо тебе знаю, щоб ділитися таким?",
        "TxtArthur_ArthurRank1Convo1_1856": "Лізти в мою особисту історію — не найліпший спосіб це зробити.",
        "TxtArthur_ArthurRank1Convo1_1859": "Та ні, усе норм… продовжуй.",
        "TxtArthur_ArthurRank1Convo1_1860": "Постав кілька запитань.",
        "TxtArthur_ArthurRank1Convo1_1861": "Я не знаю, спитай щось для початку?",
        "TxtArthur_ArthurRank1Convo1_1862": "Спершу треба придбати кілька келихів міцного.",
        "TxtArthur_ArthurRank1Convo1_1865": "Ха. Принаймні ти дуже швидко вчишся.",
        "TxtArthur_ArthurRank1Convo1_1866": "Як забажаєш.",
        "TxtArthur_ArthurRank1Convo1_1868": "Угадай.",
        "TxtArthur_ArthurRank1Convo1_1871": "Угадай.",
        "TxtArthur_ArthurRank1Convo1_1876": "Ха. Ні. Але улюблений Елеонори.",
        "TxtArthur_ArthurRank1Convo1_1877": "Ніт. Вибач.",
        "TxtArthur_ArthurRank1Convo1_1878": "Неправильно. Мені шкода.",
        "TxtArthur_ArthurRank1Convo1_1879": "Ого, з першої спроби. Звідки знаєш?",
        "TxtArthur_ArthurRank1Convo1_1880": "Чи пурпуровий?",
        "TxtArthur_ArthurRank1Convo1_1881": "Її смак змінюється.",
        "TxtArthur_ArthurRank1Convo1_1884": "Не знав, що ти з педантичних.",
        "TxtArthur_ArthurRank1Convo1_1885": "А я й не збирався тобі родинну історію переповідати, тож і не намагайся.",
        "TxtArthur_ArthurRank1Convo1_1886": "Я тебе *не знаю*.",
        "TxtArthur_ArthurRank1Convo1_1889": "Яка втрата.",
        "TxtArthur_ArthurRank1Convo1_1890": "Гадаю, тут є над чим попрацювати.",
        "TxtArthur_ArthurRank1Convo1_1891": "Це червоний.",
        "TxtArthur_ArthurRank1Convo1_1894": "Спостережливі очі.",
        "TxtArthur_ArthurRank1Convo1_1895": "Довга історія для якогось іншого дня. Після кількох ковтків міцного.",
        "TxtArthur_ArthurRank1Convo1_1897": "Це дало тобі бажані відповіді?",
        "TxtArthur_ArthurRank1Convo1_1898": "А тепер ти говориш як Елеонора.",
        "TxtArthur_ArthurRank1Convo1_1903": "Витончено, поважно.",
        "TxtArthur_ArthurRank1Convo1_1904": "Якби це було воно, то я ніколи би цього не визнав. На щастя — не воно.",
        "TxtArthur_ArthurRank1Convo1_1905": "Як… Ні. Хтось тобі сказав!",
        "TxtArthur_ArthurRank1Convo1_1906": "Хто тобі сказав?!",
        "TxtArthur_ArthurRank1Convo1_1907": "Що?! ХА-ХА!",
        "TxtArthur_ArthurRank1Convo1_1910": "Це *місце*, а не ім’я. От дурко!",
        "TxtArthur_ArthurRank1Convo1_1913": "Я зараз заплачу від реготу.",
        "TxtArthur_ArthurRank1Convo1_1914": "ПІТЕРСГЕМ!",
        "TxtArthur_ArthurRank1Convo1_1917": "Узагалі-то Джеймс. І дякую за хвилинку-веселинку.",
        "TxtArthur_ArthurRank1Convo1_1918": "Але помилка.",
        "TxtArthur_ArthurRank1Convo1_1919": "Я позбавлю тебе страждань, бо ми так змарнуємо весь день.",
        "TxtArthur_ArthurRank1Convo1_1920": "Відповідь: Джеймс.",
        "TxtArthur_ArthurRank1Convo1_1923": "Ну, не мені доводилося вибирати.",
        "TxtArthur_ArthurRank1Convo1_1928": "Ха-ха.",
        "TxtArthur_ArthurRank1Convo1_1929": "Зрозумів.",
        "TxtArthur_ArthurRank1Convo1_1931": "Щось величенький стрибок між «улюбленим кольором» та «історією родини».",
        "TxtArthur_ArthurRank1Convo1_1932": "Щось величенький стрибок між «середнім ім’ям» та «історією родини».",
        "TxtArthur_ArthurRank1Convo1_1933": "Щось величенький стрибок між «першим улюбленцем» та «історією родини».",
        "TxtArthur_ArthurRank1Convo1_1934": "Щось величенький стрибок між «дурненькими питаннями» та «історією родини».",
        "TxtArthur_ArthurRank1Convo1_1936": "Зарано.",
        "TxtArthur_ArthurRank1Convo1_1937": "Зухвала спроба.",
        "TxtArthur_ArthurRank1Convo1_3643": "Рибка, на ім’я Каламутик.",
        "TxtArthur_ArthurRank1Convo1_3644": "Я закинув його в акваріум і вода за хвилину посіріла.",
        "TxtArthur_ArthurRank1Convo1_3645": "Думав, що він спливе догори пузом.",
        "TxtArthur_ArthurRank1Convo1_3646": "Але малий халамидник прожив тринадцять років.",
        "TxtArthur_ArthurRank1Convo1_3649": "Так, я очистив кляту воду.",
        "TxtArthur_ArthurRank1Convo1_3650": "Нічого більшого мені довіряти не можна було.",
        "TxtArthur_ArthurRank1Convo1_3651": "Не такою я дитиною був. От і все.",
    }